
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Anecdote` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Anecdote
 * 
 */
export type AnecdoteModel = runtime.Types.Result.DefaultSelection<Prisma.$AnecdotePayload>

export type AggregateAnecdote = {
  _count: AnecdoteCountAggregateOutputType | null
  _avg: AnecdoteAvgAggregateOutputType | null
  _sum: AnecdoteSumAggregateOutputType | null
  _min: AnecdoteMinAggregateOutputType | null
  _max: AnecdoteMaxAggregateOutputType | null
}

export type AnecdoteAvgAggregateOutputType = {
  id: number | null
  teacherId: number | null
  studentId: number | null
}

export type AnecdoteSumAggregateOutputType = {
  id: number | null
  teacherId: number | null
  studentId: number | null
}

export type AnecdoteMinAggregateOutputType = {
  id: number | null
  content: string | null
  date: Date | null
  imageUrl: string | null
  teacherId: number | null
  studentId: number | null
}

export type AnecdoteMaxAggregateOutputType = {
  id: number | null
  content: string | null
  date: Date | null
  imageUrl: string | null
  teacherId: number | null
  studentId: number | null
}

export type AnecdoteCountAggregateOutputType = {
  id: number
  content: number
  date: number
  imageUrl: number
  teacherId: number
  studentId: number
  _all: number
}


export type AnecdoteAvgAggregateInputType = {
  id?: true
  teacherId?: true
  studentId?: true
}

export type AnecdoteSumAggregateInputType = {
  id?: true
  teacherId?: true
  studentId?: true
}

export type AnecdoteMinAggregateInputType = {
  id?: true
  content?: true
  date?: true
  imageUrl?: true
  teacherId?: true
  studentId?: true
}

export type AnecdoteMaxAggregateInputType = {
  id?: true
  content?: true
  date?: true
  imageUrl?: true
  teacherId?: true
  studentId?: true
}

export type AnecdoteCountAggregateInputType = {
  id?: true
  content?: true
  date?: true
  imageUrl?: true
  teacherId?: true
  studentId?: true
  _all?: true
}

export type AnecdoteAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Anecdote to aggregate.
   */
  where?: Prisma.AnecdoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Anecdotes to fetch.
   */
  orderBy?: Prisma.AnecdoteOrderByWithRelationInput | Prisma.AnecdoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AnecdoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Anecdotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Anecdotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Anecdotes
  **/
  _count?: true | AnecdoteCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AnecdoteAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AnecdoteSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AnecdoteMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AnecdoteMaxAggregateInputType
}

export type GetAnecdoteAggregateType<T extends AnecdoteAggregateArgs> = {
      [P in keyof T & keyof AggregateAnecdote]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAnecdote[P]>
    : Prisma.GetScalarType<T[P], AggregateAnecdote[P]>
}




export type AnecdoteGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AnecdoteWhereInput
  orderBy?: Prisma.AnecdoteOrderByWithAggregationInput | Prisma.AnecdoteOrderByWithAggregationInput[]
  by: Prisma.AnecdoteScalarFieldEnum[] | Prisma.AnecdoteScalarFieldEnum
  having?: Prisma.AnecdoteScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AnecdoteCountAggregateInputType | true
  _avg?: AnecdoteAvgAggregateInputType
  _sum?: AnecdoteSumAggregateInputType
  _min?: AnecdoteMinAggregateInputType
  _max?: AnecdoteMaxAggregateInputType
}

export type AnecdoteGroupByOutputType = {
  id: number
  content: string
  date: Date
  imageUrl: string | null
  teacherId: number
  studentId: number | null
  _count: AnecdoteCountAggregateOutputType | null
  _avg: AnecdoteAvgAggregateOutputType | null
  _sum: AnecdoteSumAggregateOutputType | null
  _min: AnecdoteMinAggregateOutputType | null
  _max: AnecdoteMaxAggregateOutputType | null
}

type GetAnecdoteGroupByPayload<T extends AnecdoteGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AnecdoteGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AnecdoteGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AnecdoteGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AnecdoteGroupByOutputType[P]>
      }
    >
  >



export type AnecdoteWhereInput = {
  AND?: Prisma.AnecdoteWhereInput | Prisma.AnecdoteWhereInput[]
  OR?: Prisma.AnecdoteWhereInput[]
  NOT?: Prisma.AnecdoteWhereInput | Prisma.AnecdoteWhereInput[]
  id?: Prisma.IntFilter<"Anecdote"> | number
  content?: Prisma.StringFilter<"Anecdote"> | string
  date?: Prisma.DateTimeFilter<"Anecdote"> | Date | string
  imageUrl?: Prisma.StringNullableFilter<"Anecdote"> | string | null
  teacherId?: Prisma.IntFilter<"Anecdote"> | number
  studentId?: Prisma.IntNullableFilter<"Anecdote"> | number | null
  teacher?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  student?: Prisma.XOR<Prisma.StudentNullableScalarRelationFilter, Prisma.StudentWhereInput> | null
}

export type AnecdoteOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  content?: Prisma.SortOrder
  date?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  teacherId?: Prisma.SortOrder
  studentId?: Prisma.SortOrderInput | Prisma.SortOrder
  teacher?: Prisma.UserOrderByWithRelationInput
  student?: Prisma.StudentOrderByWithRelationInput
  _relevance?: Prisma.AnecdoteOrderByRelevanceInput
}

export type AnecdoteWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.AnecdoteWhereInput | Prisma.AnecdoteWhereInput[]
  OR?: Prisma.AnecdoteWhereInput[]
  NOT?: Prisma.AnecdoteWhereInput | Prisma.AnecdoteWhereInput[]
  content?: Prisma.StringFilter<"Anecdote"> | string
  date?: Prisma.DateTimeFilter<"Anecdote"> | Date | string
  imageUrl?: Prisma.StringNullableFilter<"Anecdote"> | string | null
  teacherId?: Prisma.IntFilter<"Anecdote"> | number
  studentId?: Prisma.IntNullableFilter<"Anecdote"> | number | null
  teacher?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  student?: Prisma.XOR<Prisma.StudentNullableScalarRelationFilter, Prisma.StudentWhereInput> | null
}, "id">

export type AnecdoteOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  content?: Prisma.SortOrder
  date?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  teacherId?: Prisma.SortOrder
  studentId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.AnecdoteCountOrderByAggregateInput
  _avg?: Prisma.AnecdoteAvgOrderByAggregateInput
  _max?: Prisma.AnecdoteMaxOrderByAggregateInput
  _min?: Prisma.AnecdoteMinOrderByAggregateInput
  _sum?: Prisma.AnecdoteSumOrderByAggregateInput
}

export type AnecdoteScalarWhereWithAggregatesInput = {
  AND?: Prisma.AnecdoteScalarWhereWithAggregatesInput | Prisma.AnecdoteScalarWhereWithAggregatesInput[]
  OR?: Prisma.AnecdoteScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AnecdoteScalarWhereWithAggregatesInput | Prisma.AnecdoteScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Anecdote"> | number
  content?: Prisma.StringWithAggregatesFilter<"Anecdote"> | string
  date?: Prisma.DateTimeWithAggregatesFilter<"Anecdote"> | Date | string
  imageUrl?: Prisma.StringNullableWithAggregatesFilter<"Anecdote"> | string | null
  teacherId?: Prisma.IntWithAggregatesFilter<"Anecdote"> | number
  studentId?: Prisma.IntNullableWithAggregatesFilter<"Anecdote"> | number | null
}

export type AnecdoteCreateInput = {
  content: string
  date?: Date | string
  imageUrl?: string | null
  teacher: Prisma.UserCreateNestedOneWithoutAnecdotesAuthoredInput
  student?: Prisma.StudentCreateNestedOneWithoutAnecdotesInput
}

export type AnecdoteUncheckedCreateInput = {
  id?: number
  content: string
  date?: Date | string
  imageUrl?: string | null
  teacherId: number
  studentId?: number | null
}

export type AnecdoteUpdateInput = {
  content?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  teacher?: Prisma.UserUpdateOneRequiredWithoutAnecdotesAuthoredNestedInput
  student?: Prisma.StudentUpdateOneWithoutAnecdotesNestedInput
}

export type AnecdoteUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  content?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  teacherId?: Prisma.IntFieldUpdateOperationsInput | number
  studentId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type AnecdoteCreateManyInput = {
  id?: number
  content: string
  date?: Date | string
  imageUrl?: string | null
  teacherId: number
  studentId?: number | null
}

export type AnecdoteUpdateManyMutationInput = {
  content?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AnecdoteUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  content?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  teacherId?: Prisma.IntFieldUpdateOperationsInput | number
  studentId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type AnecdoteListRelationFilter = {
  every?: Prisma.AnecdoteWhereInput
  some?: Prisma.AnecdoteWhereInput
  none?: Prisma.AnecdoteWhereInput
}

export type AnecdoteOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AnecdoteOrderByRelevanceInput = {
  fields: Prisma.AnecdoteOrderByRelevanceFieldEnum | Prisma.AnecdoteOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type AnecdoteCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  content?: Prisma.SortOrder
  date?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  teacherId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
}

export type AnecdoteAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  teacherId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
}

export type AnecdoteMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  content?: Prisma.SortOrder
  date?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  teacherId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
}

export type AnecdoteMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  content?: Prisma.SortOrder
  date?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  teacherId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
}

export type AnecdoteSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  teacherId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
}

export type AnecdoteCreateNestedManyWithoutTeacherInput = {
  create?: Prisma.XOR<Prisma.AnecdoteCreateWithoutTeacherInput, Prisma.AnecdoteUncheckedCreateWithoutTeacherInput> | Prisma.AnecdoteCreateWithoutTeacherInput[] | Prisma.AnecdoteUncheckedCreateWithoutTeacherInput[]
  connectOrCreate?: Prisma.AnecdoteCreateOrConnectWithoutTeacherInput | Prisma.AnecdoteCreateOrConnectWithoutTeacherInput[]
  createMany?: Prisma.AnecdoteCreateManyTeacherInputEnvelope
  connect?: Prisma.AnecdoteWhereUniqueInput | Prisma.AnecdoteWhereUniqueInput[]
}

export type AnecdoteUncheckedCreateNestedManyWithoutTeacherInput = {
  create?: Prisma.XOR<Prisma.AnecdoteCreateWithoutTeacherInput, Prisma.AnecdoteUncheckedCreateWithoutTeacherInput> | Prisma.AnecdoteCreateWithoutTeacherInput[] | Prisma.AnecdoteUncheckedCreateWithoutTeacherInput[]
  connectOrCreate?: Prisma.AnecdoteCreateOrConnectWithoutTeacherInput | Prisma.AnecdoteCreateOrConnectWithoutTeacherInput[]
  createMany?: Prisma.AnecdoteCreateManyTeacherInputEnvelope
  connect?: Prisma.AnecdoteWhereUniqueInput | Prisma.AnecdoteWhereUniqueInput[]
}

export type AnecdoteUpdateManyWithoutTeacherNestedInput = {
  create?: Prisma.XOR<Prisma.AnecdoteCreateWithoutTeacherInput, Prisma.AnecdoteUncheckedCreateWithoutTeacherInput> | Prisma.AnecdoteCreateWithoutTeacherInput[] | Prisma.AnecdoteUncheckedCreateWithoutTeacherInput[]
  connectOrCreate?: Prisma.AnecdoteCreateOrConnectWithoutTeacherInput | Prisma.AnecdoteCreateOrConnectWithoutTeacherInput[]
  upsert?: Prisma.AnecdoteUpsertWithWhereUniqueWithoutTeacherInput | Prisma.AnecdoteUpsertWithWhereUniqueWithoutTeacherInput[]
  createMany?: Prisma.AnecdoteCreateManyTeacherInputEnvelope
  set?: Prisma.AnecdoteWhereUniqueInput | Prisma.AnecdoteWhereUniqueInput[]
  disconnect?: Prisma.AnecdoteWhereUniqueInput | Prisma.AnecdoteWhereUniqueInput[]
  delete?: Prisma.AnecdoteWhereUniqueInput | Prisma.AnecdoteWhereUniqueInput[]
  connect?: Prisma.AnecdoteWhereUniqueInput | Prisma.AnecdoteWhereUniqueInput[]
  update?: Prisma.AnecdoteUpdateWithWhereUniqueWithoutTeacherInput | Prisma.AnecdoteUpdateWithWhereUniqueWithoutTeacherInput[]
  updateMany?: Prisma.AnecdoteUpdateManyWithWhereWithoutTeacherInput | Prisma.AnecdoteUpdateManyWithWhereWithoutTeacherInput[]
  deleteMany?: Prisma.AnecdoteScalarWhereInput | Prisma.AnecdoteScalarWhereInput[]
}

export type AnecdoteUncheckedUpdateManyWithoutTeacherNestedInput = {
  create?: Prisma.XOR<Prisma.AnecdoteCreateWithoutTeacherInput, Prisma.AnecdoteUncheckedCreateWithoutTeacherInput> | Prisma.AnecdoteCreateWithoutTeacherInput[] | Prisma.AnecdoteUncheckedCreateWithoutTeacherInput[]
  connectOrCreate?: Prisma.AnecdoteCreateOrConnectWithoutTeacherInput | Prisma.AnecdoteCreateOrConnectWithoutTeacherInput[]
  upsert?: Prisma.AnecdoteUpsertWithWhereUniqueWithoutTeacherInput | Prisma.AnecdoteUpsertWithWhereUniqueWithoutTeacherInput[]
  createMany?: Prisma.AnecdoteCreateManyTeacherInputEnvelope
  set?: Prisma.AnecdoteWhereUniqueInput | Prisma.AnecdoteWhereUniqueInput[]
  disconnect?: Prisma.AnecdoteWhereUniqueInput | Prisma.AnecdoteWhereUniqueInput[]
  delete?: Prisma.AnecdoteWhereUniqueInput | Prisma.AnecdoteWhereUniqueInput[]
  connect?: Prisma.AnecdoteWhereUniqueInput | Prisma.AnecdoteWhereUniqueInput[]
  update?: Prisma.AnecdoteUpdateWithWhereUniqueWithoutTeacherInput | Prisma.AnecdoteUpdateWithWhereUniqueWithoutTeacherInput[]
  updateMany?: Prisma.AnecdoteUpdateManyWithWhereWithoutTeacherInput | Prisma.AnecdoteUpdateManyWithWhereWithoutTeacherInput[]
  deleteMany?: Prisma.AnecdoteScalarWhereInput | Prisma.AnecdoteScalarWhereInput[]
}

export type AnecdoteCreateNestedManyWithoutStudentInput = {
  create?: Prisma.XOR<Prisma.AnecdoteCreateWithoutStudentInput, Prisma.AnecdoteUncheckedCreateWithoutStudentInput> | Prisma.AnecdoteCreateWithoutStudentInput[] | Prisma.AnecdoteUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.AnecdoteCreateOrConnectWithoutStudentInput | Prisma.AnecdoteCreateOrConnectWithoutStudentInput[]
  createMany?: Prisma.AnecdoteCreateManyStudentInputEnvelope
  connect?: Prisma.AnecdoteWhereUniqueInput | Prisma.AnecdoteWhereUniqueInput[]
}

export type AnecdoteUncheckedCreateNestedManyWithoutStudentInput = {
  create?: Prisma.XOR<Prisma.AnecdoteCreateWithoutStudentInput, Prisma.AnecdoteUncheckedCreateWithoutStudentInput> | Prisma.AnecdoteCreateWithoutStudentInput[] | Prisma.AnecdoteUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.AnecdoteCreateOrConnectWithoutStudentInput | Prisma.AnecdoteCreateOrConnectWithoutStudentInput[]
  createMany?: Prisma.AnecdoteCreateManyStudentInputEnvelope
  connect?: Prisma.AnecdoteWhereUniqueInput | Prisma.AnecdoteWhereUniqueInput[]
}

export type AnecdoteUpdateManyWithoutStudentNestedInput = {
  create?: Prisma.XOR<Prisma.AnecdoteCreateWithoutStudentInput, Prisma.AnecdoteUncheckedCreateWithoutStudentInput> | Prisma.AnecdoteCreateWithoutStudentInput[] | Prisma.AnecdoteUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.AnecdoteCreateOrConnectWithoutStudentInput | Prisma.AnecdoteCreateOrConnectWithoutStudentInput[]
  upsert?: Prisma.AnecdoteUpsertWithWhereUniqueWithoutStudentInput | Prisma.AnecdoteUpsertWithWhereUniqueWithoutStudentInput[]
  createMany?: Prisma.AnecdoteCreateManyStudentInputEnvelope
  set?: Prisma.AnecdoteWhereUniqueInput | Prisma.AnecdoteWhereUniqueInput[]
  disconnect?: Prisma.AnecdoteWhereUniqueInput | Prisma.AnecdoteWhereUniqueInput[]
  delete?: Prisma.AnecdoteWhereUniqueInput | Prisma.AnecdoteWhereUniqueInput[]
  connect?: Prisma.AnecdoteWhereUniqueInput | Prisma.AnecdoteWhereUniqueInput[]
  update?: Prisma.AnecdoteUpdateWithWhereUniqueWithoutStudentInput | Prisma.AnecdoteUpdateWithWhereUniqueWithoutStudentInput[]
  updateMany?: Prisma.AnecdoteUpdateManyWithWhereWithoutStudentInput | Prisma.AnecdoteUpdateManyWithWhereWithoutStudentInput[]
  deleteMany?: Prisma.AnecdoteScalarWhereInput | Prisma.AnecdoteScalarWhereInput[]
}

export type AnecdoteUncheckedUpdateManyWithoutStudentNestedInput = {
  create?: Prisma.XOR<Prisma.AnecdoteCreateWithoutStudentInput, Prisma.AnecdoteUncheckedCreateWithoutStudentInput> | Prisma.AnecdoteCreateWithoutStudentInput[] | Prisma.AnecdoteUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.AnecdoteCreateOrConnectWithoutStudentInput | Prisma.AnecdoteCreateOrConnectWithoutStudentInput[]
  upsert?: Prisma.AnecdoteUpsertWithWhereUniqueWithoutStudentInput | Prisma.AnecdoteUpsertWithWhereUniqueWithoutStudentInput[]
  createMany?: Prisma.AnecdoteCreateManyStudentInputEnvelope
  set?: Prisma.AnecdoteWhereUniqueInput | Prisma.AnecdoteWhereUniqueInput[]
  disconnect?: Prisma.AnecdoteWhereUniqueInput | Prisma.AnecdoteWhereUniqueInput[]
  delete?: Prisma.AnecdoteWhereUniqueInput | Prisma.AnecdoteWhereUniqueInput[]
  connect?: Prisma.AnecdoteWhereUniqueInput | Prisma.AnecdoteWhereUniqueInput[]
  update?: Prisma.AnecdoteUpdateWithWhereUniqueWithoutStudentInput | Prisma.AnecdoteUpdateWithWhereUniqueWithoutStudentInput[]
  updateMany?: Prisma.AnecdoteUpdateManyWithWhereWithoutStudentInput | Prisma.AnecdoteUpdateManyWithWhereWithoutStudentInput[]
  deleteMany?: Prisma.AnecdoteScalarWhereInput | Prisma.AnecdoteScalarWhereInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type AnecdoteCreateWithoutTeacherInput = {
  content: string
  date?: Date | string
  imageUrl?: string | null
  student?: Prisma.StudentCreateNestedOneWithoutAnecdotesInput
}

export type AnecdoteUncheckedCreateWithoutTeacherInput = {
  id?: number
  content: string
  date?: Date | string
  imageUrl?: string | null
  studentId?: number | null
}

export type AnecdoteCreateOrConnectWithoutTeacherInput = {
  where: Prisma.AnecdoteWhereUniqueInput
  create: Prisma.XOR<Prisma.AnecdoteCreateWithoutTeacherInput, Prisma.AnecdoteUncheckedCreateWithoutTeacherInput>
}

export type AnecdoteCreateManyTeacherInputEnvelope = {
  data: Prisma.AnecdoteCreateManyTeacherInput | Prisma.AnecdoteCreateManyTeacherInput[]
  skipDuplicates?: boolean
}

export type AnecdoteUpsertWithWhereUniqueWithoutTeacherInput = {
  where: Prisma.AnecdoteWhereUniqueInput
  update: Prisma.XOR<Prisma.AnecdoteUpdateWithoutTeacherInput, Prisma.AnecdoteUncheckedUpdateWithoutTeacherInput>
  create: Prisma.XOR<Prisma.AnecdoteCreateWithoutTeacherInput, Prisma.AnecdoteUncheckedCreateWithoutTeacherInput>
}

export type AnecdoteUpdateWithWhereUniqueWithoutTeacherInput = {
  where: Prisma.AnecdoteWhereUniqueInput
  data: Prisma.XOR<Prisma.AnecdoteUpdateWithoutTeacherInput, Prisma.AnecdoteUncheckedUpdateWithoutTeacherInput>
}

export type AnecdoteUpdateManyWithWhereWithoutTeacherInput = {
  where: Prisma.AnecdoteScalarWhereInput
  data: Prisma.XOR<Prisma.AnecdoteUpdateManyMutationInput, Prisma.AnecdoteUncheckedUpdateManyWithoutTeacherInput>
}

export type AnecdoteScalarWhereInput = {
  AND?: Prisma.AnecdoteScalarWhereInput | Prisma.AnecdoteScalarWhereInput[]
  OR?: Prisma.AnecdoteScalarWhereInput[]
  NOT?: Prisma.AnecdoteScalarWhereInput | Prisma.AnecdoteScalarWhereInput[]
  id?: Prisma.IntFilter<"Anecdote"> | number
  content?: Prisma.StringFilter<"Anecdote"> | string
  date?: Prisma.DateTimeFilter<"Anecdote"> | Date | string
  imageUrl?: Prisma.StringNullableFilter<"Anecdote"> | string | null
  teacherId?: Prisma.IntFilter<"Anecdote"> | number
  studentId?: Prisma.IntNullableFilter<"Anecdote"> | number | null
}

export type AnecdoteCreateWithoutStudentInput = {
  content: string
  date?: Date | string
  imageUrl?: string | null
  teacher: Prisma.UserCreateNestedOneWithoutAnecdotesAuthoredInput
}

export type AnecdoteUncheckedCreateWithoutStudentInput = {
  id?: number
  content: string
  date?: Date | string
  imageUrl?: string | null
  teacherId: number
}

export type AnecdoteCreateOrConnectWithoutStudentInput = {
  where: Prisma.AnecdoteWhereUniqueInput
  create: Prisma.XOR<Prisma.AnecdoteCreateWithoutStudentInput, Prisma.AnecdoteUncheckedCreateWithoutStudentInput>
}

export type AnecdoteCreateManyStudentInputEnvelope = {
  data: Prisma.AnecdoteCreateManyStudentInput | Prisma.AnecdoteCreateManyStudentInput[]
  skipDuplicates?: boolean
}

export type AnecdoteUpsertWithWhereUniqueWithoutStudentInput = {
  where: Prisma.AnecdoteWhereUniqueInput
  update: Prisma.XOR<Prisma.AnecdoteUpdateWithoutStudentInput, Prisma.AnecdoteUncheckedUpdateWithoutStudentInput>
  create: Prisma.XOR<Prisma.AnecdoteCreateWithoutStudentInput, Prisma.AnecdoteUncheckedCreateWithoutStudentInput>
}

export type AnecdoteUpdateWithWhereUniqueWithoutStudentInput = {
  where: Prisma.AnecdoteWhereUniqueInput
  data: Prisma.XOR<Prisma.AnecdoteUpdateWithoutStudentInput, Prisma.AnecdoteUncheckedUpdateWithoutStudentInput>
}

export type AnecdoteUpdateManyWithWhereWithoutStudentInput = {
  where: Prisma.AnecdoteScalarWhereInput
  data: Prisma.XOR<Prisma.AnecdoteUpdateManyMutationInput, Prisma.AnecdoteUncheckedUpdateManyWithoutStudentInput>
}

export type AnecdoteCreateManyTeacherInput = {
  id?: number
  content: string
  date?: Date | string
  imageUrl?: string | null
  studentId?: number | null
}

export type AnecdoteUpdateWithoutTeacherInput = {
  content?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  student?: Prisma.StudentUpdateOneWithoutAnecdotesNestedInput
}

export type AnecdoteUncheckedUpdateWithoutTeacherInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  content?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  studentId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type AnecdoteUncheckedUpdateManyWithoutTeacherInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  content?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  studentId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type AnecdoteCreateManyStudentInput = {
  id?: number
  content: string
  date?: Date | string
  imageUrl?: string | null
  teacherId: number
}

export type AnecdoteUpdateWithoutStudentInput = {
  content?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  teacher?: Prisma.UserUpdateOneRequiredWithoutAnecdotesAuthoredNestedInput
}

export type AnecdoteUncheckedUpdateWithoutStudentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  content?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  teacherId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AnecdoteUncheckedUpdateManyWithoutStudentInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  content?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  teacherId?: Prisma.IntFieldUpdateOperationsInput | number
}



export type AnecdoteSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  content?: boolean
  date?: boolean
  imageUrl?: boolean
  teacherId?: boolean
  studentId?: boolean
  teacher?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  student?: boolean | Prisma.Anecdote$studentArgs<ExtArgs>
}, ExtArgs["result"]["anecdote"]>



export type AnecdoteSelectScalar = {
  id?: boolean
  content?: boolean
  date?: boolean
  imageUrl?: boolean
  teacherId?: boolean
  studentId?: boolean
}

export type AnecdoteOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "content" | "date" | "imageUrl" | "teacherId" | "studentId", ExtArgs["result"]["anecdote"]>
export type AnecdoteInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  teacher?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  student?: boolean | Prisma.Anecdote$studentArgs<ExtArgs>
}

export type $AnecdotePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Anecdote"
  objects: {
    teacher: Prisma.$UserPayload<ExtArgs>
    student: Prisma.$StudentPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    content: string
    date: Date
    imageUrl: string | null
    teacherId: number
    studentId: number | null
  }, ExtArgs["result"]["anecdote"]>
  composites: {}
}

export type AnecdoteGetPayload<S extends boolean | null | undefined | AnecdoteDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AnecdotePayload, S>

export type AnecdoteCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AnecdoteFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AnecdoteCountAggregateInputType | true
  }

export interface AnecdoteDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Anecdote'], meta: { name: 'Anecdote' } }
  /**
   * Find zero or one Anecdote that matches the filter.
   * @param {AnecdoteFindUniqueArgs} args - Arguments to find a Anecdote
   * @example
   * // Get one Anecdote
   * const anecdote = await prisma.anecdote.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AnecdoteFindUniqueArgs>(args: Prisma.SelectSubset<T, AnecdoteFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AnecdoteClient<runtime.Types.Result.GetResult<Prisma.$AnecdotePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Anecdote that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AnecdoteFindUniqueOrThrowArgs} args - Arguments to find a Anecdote
   * @example
   * // Get one Anecdote
   * const anecdote = await prisma.anecdote.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AnecdoteFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AnecdoteFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AnecdoteClient<runtime.Types.Result.GetResult<Prisma.$AnecdotePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Anecdote that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnecdoteFindFirstArgs} args - Arguments to find a Anecdote
   * @example
   * // Get one Anecdote
   * const anecdote = await prisma.anecdote.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AnecdoteFindFirstArgs>(args?: Prisma.SelectSubset<T, AnecdoteFindFirstArgs<ExtArgs>>): Prisma.Prisma__AnecdoteClient<runtime.Types.Result.GetResult<Prisma.$AnecdotePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Anecdote that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnecdoteFindFirstOrThrowArgs} args - Arguments to find a Anecdote
   * @example
   * // Get one Anecdote
   * const anecdote = await prisma.anecdote.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AnecdoteFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AnecdoteFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AnecdoteClient<runtime.Types.Result.GetResult<Prisma.$AnecdotePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Anecdotes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnecdoteFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Anecdotes
   * const anecdotes = await prisma.anecdote.findMany()
   * 
   * // Get first 10 Anecdotes
   * const anecdotes = await prisma.anecdote.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const anecdoteWithIdOnly = await prisma.anecdote.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AnecdoteFindManyArgs>(args?: Prisma.SelectSubset<T, AnecdoteFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AnecdotePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Anecdote.
   * @param {AnecdoteCreateArgs} args - Arguments to create a Anecdote.
   * @example
   * // Create one Anecdote
   * const Anecdote = await prisma.anecdote.create({
   *   data: {
   *     // ... data to create a Anecdote
   *   }
   * })
   * 
   */
  create<T extends AnecdoteCreateArgs>(args: Prisma.SelectSubset<T, AnecdoteCreateArgs<ExtArgs>>): Prisma.Prisma__AnecdoteClient<runtime.Types.Result.GetResult<Prisma.$AnecdotePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Anecdotes.
   * @param {AnecdoteCreateManyArgs} args - Arguments to create many Anecdotes.
   * @example
   * // Create many Anecdotes
   * const anecdote = await prisma.anecdote.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AnecdoteCreateManyArgs>(args?: Prisma.SelectSubset<T, AnecdoteCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Anecdote.
   * @param {AnecdoteDeleteArgs} args - Arguments to delete one Anecdote.
   * @example
   * // Delete one Anecdote
   * const Anecdote = await prisma.anecdote.delete({
   *   where: {
   *     // ... filter to delete one Anecdote
   *   }
   * })
   * 
   */
  delete<T extends AnecdoteDeleteArgs>(args: Prisma.SelectSubset<T, AnecdoteDeleteArgs<ExtArgs>>): Prisma.Prisma__AnecdoteClient<runtime.Types.Result.GetResult<Prisma.$AnecdotePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Anecdote.
   * @param {AnecdoteUpdateArgs} args - Arguments to update one Anecdote.
   * @example
   * // Update one Anecdote
   * const anecdote = await prisma.anecdote.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AnecdoteUpdateArgs>(args: Prisma.SelectSubset<T, AnecdoteUpdateArgs<ExtArgs>>): Prisma.Prisma__AnecdoteClient<runtime.Types.Result.GetResult<Prisma.$AnecdotePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Anecdotes.
   * @param {AnecdoteDeleteManyArgs} args - Arguments to filter Anecdotes to delete.
   * @example
   * // Delete a few Anecdotes
   * const { count } = await prisma.anecdote.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AnecdoteDeleteManyArgs>(args?: Prisma.SelectSubset<T, AnecdoteDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Anecdotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnecdoteUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Anecdotes
   * const anecdote = await prisma.anecdote.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AnecdoteUpdateManyArgs>(args: Prisma.SelectSubset<T, AnecdoteUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Anecdote.
   * @param {AnecdoteUpsertArgs} args - Arguments to update or create a Anecdote.
   * @example
   * // Update or create a Anecdote
   * const anecdote = await prisma.anecdote.upsert({
   *   create: {
   *     // ... data to create a Anecdote
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Anecdote we want to update
   *   }
   * })
   */
  upsert<T extends AnecdoteUpsertArgs>(args: Prisma.SelectSubset<T, AnecdoteUpsertArgs<ExtArgs>>): Prisma.Prisma__AnecdoteClient<runtime.Types.Result.GetResult<Prisma.$AnecdotePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Anecdotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnecdoteCountArgs} args - Arguments to filter Anecdotes to count.
   * @example
   * // Count the number of Anecdotes
   * const count = await prisma.anecdote.count({
   *   where: {
   *     // ... the filter for the Anecdotes we want to count
   *   }
   * })
  **/
  count<T extends AnecdoteCountArgs>(
    args?: Prisma.Subset<T, AnecdoteCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AnecdoteCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Anecdote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnecdoteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AnecdoteAggregateArgs>(args: Prisma.Subset<T, AnecdoteAggregateArgs>): Prisma.PrismaPromise<GetAnecdoteAggregateType<T>>

  /**
   * Group by Anecdote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnecdoteGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AnecdoteGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AnecdoteGroupByArgs['orderBy'] }
      : { orderBy?: AnecdoteGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AnecdoteGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAnecdoteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Anecdote model
 */
readonly fields: AnecdoteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Anecdote.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AnecdoteClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  teacher<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  student<T extends Prisma.Anecdote$studentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Anecdote$studentArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Anecdote model
 */
export interface AnecdoteFieldRefs {
  readonly id: Prisma.FieldRef<"Anecdote", 'Int'>
  readonly content: Prisma.FieldRef<"Anecdote", 'String'>
  readonly date: Prisma.FieldRef<"Anecdote", 'DateTime'>
  readonly imageUrl: Prisma.FieldRef<"Anecdote", 'String'>
  readonly teacherId: Prisma.FieldRef<"Anecdote", 'Int'>
  readonly studentId: Prisma.FieldRef<"Anecdote", 'Int'>
}
    

// Custom InputTypes
/**
 * Anecdote findUnique
 */
export type AnecdoteFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Anecdote
   */
  select?: Prisma.AnecdoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Anecdote
   */
  omit?: Prisma.AnecdoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnecdoteInclude<ExtArgs> | null
  /**
   * Filter, which Anecdote to fetch.
   */
  where: Prisma.AnecdoteWhereUniqueInput
}

/**
 * Anecdote findUniqueOrThrow
 */
export type AnecdoteFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Anecdote
   */
  select?: Prisma.AnecdoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Anecdote
   */
  omit?: Prisma.AnecdoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnecdoteInclude<ExtArgs> | null
  /**
   * Filter, which Anecdote to fetch.
   */
  where: Prisma.AnecdoteWhereUniqueInput
}

/**
 * Anecdote findFirst
 */
export type AnecdoteFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Anecdote
   */
  select?: Prisma.AnecdoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Anecdote
   */
  omit?: Prisma.AnecdoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnecdoteInclude<ExtArgs> | null
  /**
   * Filter, which Anecdote to fetch.
   */
  where?: Prisma.AnecdoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Anecdotes to fetch.
   */
  orderBy?: Prisma.AnecdoteOrderByWithRelationInput | Prisma.AnecdoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Anecdotes.
   */
  cursor?: Prisma.AnecdoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Anecdotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Anecdotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Anecdotes.
   */
  distinct?: Prisma.AnecdoteScalarFieldEnum | Prisma.AnecdoteScalarFieldEnum[]
}

/**
 * Anecdote findFirstOrThrow
 */
export type AnecdoteFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Anecdote
   */
  select?: Prisma.AnecdoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Anecdote
   */
  omit?: Prisma.AnecdoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnecdoteInclude<ExtArgs> | null
  /**
   * Filter, which Anecdote to fetch.
   */
  where?: Prisma.AnecdoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Anecdotes to fetch.
   */
  orderBy?: Prisma.AnecdoteOrderByWithRelationInput | Prisma.AnecdoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Anecdotes.
   */
  cursor?: Prisma.AnecdoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Anecdotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Anecdotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Anecdotes.
   */
  distinct?: Prisma.AnecdoteScalarFieldEnum | Prisma.AnecdoteScalarFieldEnum[]
}

/**
 * Anecdote findMany
 */
export type AnecdoteFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Anecdote
   */
  select?: Prisma.AnecdoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Anecdote
   */
  omit?: Prisma.AnecdoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnecdoteInclude<ExtArgs> | null
  /**
   * Filter, which Anecdotes to fetch.
   */
  where?: Prisma.AnecdoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Anecdotes to fetch.
   */
  orderBy?: Prisma.AnecdoteOrderByWithRelationInput | Prisma.AnecdoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Anecdotes.
   */
  cursor?: Prisma.AnecdoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Anecdotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Anecdotes.
   */
  skip?: number
  distinct?: Prisma.AnecdoteScalarFieldEnum | Prisma.AnecdoteScalarFieldEnum[]
}

/**
 * Anecdote create
 */
export type AnecdoteCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Anecdote
   */
  select?: Prisma.AnecdoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Anecdote
   */
  omit?: Prisma.AnecdoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnecdoteInclude<ExtArgs> | null
  /**
   * The data needed to create a Anecdote.
   */
  data: Prisma.XOR<Prisma.AnecdoteCreateInput, Prisma.AnecdoteUncheckedCreateInput>
}

/**
 * Anecdote createMany
 */
export type AnecdoteCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Anecdotes.
   */
  data: Prisma.AnecdoteCreateManyInput | Prisma.AnecdoteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Anecdote update
 */
export type AnecdoteUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Anecdote
   */
  select?: Prisma.AnecdoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Anecdote
   */
  omit?: Prisma.AnecdoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnecdoteInclude<ExtArgs> | null
  /**
   * The data needed to update a Anecdote.
   */
  data: Prisma.XOR<Prisma.AnecdoteUpdateInput, Prisma.AnecdoteUncheckedUpdateInput>
  /**
   * Choose, which Anecdote to update.
   */
  where: Prisma.AnecdoteWhereUniqueInput
}

/**
 * Anecdote updateMany
 */
export type AnecdoteUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Anecdotes.
   */
  data: Prisma.XOR<Prisma.AnecdoteUpdateManyMutationInput, Prisma.AnecdoteUncheckedUpdateManyInput>
  /**
   * Filter which Anecdotes to update
   */
  where?: Prisma.AnecdoteWhereInput
  /**
   * Limit how many Anecdotes to update.
   */
  limit?: number
}

/**
 * Anecdote upsert
 */
export type AnecdoteUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Anecdote
   */
  select?: Prisma.AnecdoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Anecdote
   */
  omit?: Prisma.AnecdoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnecdoteInclude<ExtArgs> | null
  /**
   * The filter to search for the Anecdote to update in case it exists.
   */
  where: Prisma.AnecdoteWhereUniqueInput
  /**
   * In case the Anecdote found by the `where` argument doesn't exist, create a new Anecdote with this data.
   */
  create: Prisma.XOR<Prisma.AnecdoteCreateInput, Prisma.AnecdoteUncheckedCreateInput>
  /**
   * In case the Anecdote was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AnecdoteUpdateInput, Prisma.AnecdoteUncheckedUpdateInput>
}

/**
 * Anecdote delete
 */
export type AnecdoteDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Anecdote
   */
  select?: Prisma.AnecdoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Anecdote
   */
  omit?: Prisma.AnecdoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnecdoteInclude<ExtArgs> | null
  /**
   * Filter which Anecdote to delete.
   */
  where: Prisma.AnecdoteWhereUniqueInput
}

/**
 * Anecdote deleteMany
 */
export type AnecdoteDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Anecdotes to delete
   */
  where?: Prisma.AnecdoteWhereInput
  /**
   * Limit how many Anecdotes to delete.
   */
  limit?: number
}

/**
 * Anecdote.student
 */
export type Anecdote$studentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Student
   */
  select?: Prisma.StudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Student
   */
  omit?: Prisma.StudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentInclude<ExtArgs> | null
  where?: Prisma.StudentWhereInput
}

/**
 * Anecdote without action
 */
export type AnecdoteDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Anecdote
   */
  select?: Prisma.AnecdoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Anecdote
   */
  omit?: Prisma.AnecdoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnecdoteInclude<ExtArgs> | null
}
