
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Ape` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Ape
 * 
 */
export type ApeModel = runtime.Types.Result.DefaultSelection<Prisma.$ApePayload>

export type AggregateApe = {
  _count: ApeCountAggregateOutputType | null
  _avg: ApeAvgAggregateOutputType | null
  _sum: ApeSumAggregateOutputType | null
  _min: ApeMinAggregateOutputType | null
  _max: ApeMaxAggregateOutputType | null
}

export type ApeAvgAggregateOutputType = {
  id: number | null
  quantity: number | null
  updatedById: number | null
}

export type ApeSumAggregateOutputType = {
  id: number | null
  quantity: number | null
  updatedById: number | null
}

export type ApeMinAggregateOutputType = {
  id: number | null
  name: string | null
  condition: string | null
  quantity: number | null
  location: string | null
  updatedAt: Date | null
  updatedById: number | null
}

export type ApeMaxAggregateOutputType = {
  id: number | null
  name: string | null
  condition: string | null
  quantity: number | null
  location: string | null
  updatedAt: Date | null
  updatedById: number | null
}

export type ApeCountAggregateOutputType = {
  id: number
  name: number
  condition: number
  quantity: number
  location: number
  updatedAt: number
  updatedById: number
  _all: number
}


export type ApeAvgAggregateInputType = {
  id?: true
  quantity?: true
  updatedById?: true
}

export type ApeSumAggregateInputType = {
  id?: true
  quantity?: true
  updatedById?: true
}

export type ApeMinAggregateInputType = {
  id?: true
  name?: true
  condition?: true
  quantity?: true
  location?: true
  updatedAt?: true
  updatedById?: true
}

export type ApeMaxAggregateInputType = {
  id?: true
  name?: true
  condition?: true
  quantity?: true
  location?: true
  updatedAt?: true
  updatedById?: true
}

export type ApeCountAggregateInputType = {
  id?: true
  name?: true
  condition?: true
  quantity?: true
  location?: true
  updatedAt?: true
  updatedById?: true
  _all?: true
}

export type ApeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Ape to aggregate.
   */
  where?: Prisma.ApeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Apes to fetch.
   */
  orderBy?: Prisma.ApeOrderByWithRelationInput | Prisma.ApeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ApeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Apes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Apes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Apes
  **/
  _count?: true | ApeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ApeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ApeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ApeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ApeMaxAggregateInputType
}

export type GetApeAggregateType<T extends ApeAggregateArgs> = {
      [P in keyof T & keyof AggregateApe]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateApe[P]>
    : Prisma.GetScalarType<T[P], AggregateApe[P]>
}




export type ApeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ApeWhereInput
  orderBy?: Prisma.ApeOrderByWithAggregationInput | Prisma.ApeOrderByWithAggregationInput[]
  by: Prisma.ApeScalarFieldEnum[] | Prisma.ApeScalarFieldEnum
  having?: Prisma.ApeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ApeCountAggregateInputType | true
  _avg?: ApeAvgAggregateInputType
  _sum?: ApeSumAggregateInputType
  _min?: ApeMinAggregateInputType
  _max?: ApeMaxAggregateInputType
}

export type ApeGroupByOutputType = {
  id: number
  name: string
  condition: string | null
  quantity: number
  location: string | null
  updatedAt: Date
  updatedById: number
  _count: ApeCountAggregateOutputType | null
  _avg: ApeAvgAggregateOutputType | null
  _sum: ApeSumAggregateOutputType | null
  _min: ApeMinAggregateOutputType | null
  _max: ApeMaxAggregateOutputType | null
}

type GetApeGroupByPayload<T extends ApeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ApeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ApeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ApeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ApeGroupByOutputType[P]>
      }
    >
  >



export type ApeWhereInput = {
  AND?: Prisma.ApeWhereInput | Prisma.ApeWhereInput[]
  OR?: Prisma.ApeWhereInput[]
  NOT?: Prisma.ApeWhereInput | Prisma.ApeWhereInput[]
  id?: Prisma.IntFilter<"Ape"> | number
  name?: Prisma.StringFilter<"Ape"> | string
  condition?: Prisma.StringNullableFilter<"Ape"> | string | null
  quantity?: Prisma.IntFilter<"Ape"> | number
  location?: Prisma.StringNullableFilter<"Ape"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"Ape"> | Date | string
  updatedById?: Prisma.IntFilter<"Ape"> | number
  updatedBy?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type ApeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  condition?: Prisma.SortOrderInput | Prisma.SortOrder
  quantity?: Prisma.SortOrder
  location?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  updatedById?: Prisma.SortOrder
  updatedBy?: Prisma.UserOrderByWithRelationInput
  _relevance?: Prisma.ApeOrderByRelevanceInput
}

export type ApeWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ApeWhereInput | Prisma.ApeWhereInput[]
  OR?: Prisma.ApeWhereInput[]
  NOT?: Prisma.ApeWhereInput | Prisma.ApeWhereInput[]
  name?: Prisma.StringFilter<"Ape"> | string
  condition?: Prisma.StringNullableFilter<"Ape"> | string | null
  quantity?: Prisma.IntFilter<"Ape"> | number
  location?: Prisma.StringNullableFilter<"Ape"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"Ape"> | Date | string
  updatedById?: Prisma.IntFilter<"Ape"> | number
  updatedBy?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type ApeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  condition?: Prisma.SortOrderInput | Prisma.SortOrder
  quantity?: Prisma.SortOrder
  location?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  updatedById?: Prisma.SortOrder
  _count?: Prisma.ApeCountOrderByAggregateInput
  _avg?: Prisma.ApeAvgOrderByAggregateInput
  _max?: Prisma.ApeMaxOrderByAggregateInput
  _min?: Prisma.ApeMinOrderByAggregateInput
  _sum?: Prisma.ApeSumOrderByAggregateInput
}

export type ApeScalarWhereWithAggregatesInput = {
  AND?: Prisma.ApeScalarWhereWithAggregatesInput | Prisma.ApeScalarWhereWithAggregatesInput[]
  OR?: Prisma.ApeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ApeScalarWhereWithAggregatesInput | Prisma.ApeScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Ape"> | number
  name?: Prisma.StringWithAggregatesFilter<"Ape"> | string
  condition?: Prisma.StringNullableWithAggregatesFilter<"Ape"> | string | null
  quantity?: Prisma.IntWithAggregatesFilter<"Ape"> | number
  location?: Prisma.StringNullableWithAggregatesFilter<"Ape"> | string | null
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Ape"> | Date | string
  updatedById?: Prisma.IntWithAggregatesFilter<"Ape"> | number
}

export type ApeCreateInput = {
  name: string
  condition?: string | null
  quantity?: number
  location?: string | null
  updatedAt?: Date | string
  updatedBy: Prisma.UserCreateNestedOneWithoutApeUpdatedInput
}

export type ApeUncheckedCreateInput = {
  id?: number
  name: string
  condition?: string | null
  quantity?: number
  location?: string | null
  updatedAt?: Date | string
  updatedById: number
}

export type ApeUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  condition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedBy?: Prisma.UserUpdateOneRequiredWithoutApeUpdatedNestedInput
}

export type ApeUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  condition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedById?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ApeCreateManyInput = {
  id?: number
  name: string
  condition?: string | null
  quantity?: number
  location?: string | null
  updatedAt?: Date | string
  updatedById: number
}

export type ApeUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  condition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApeUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  condition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedById?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ApeListRelationFilter = {
  every?: Prisma.ApeWhereInput
  some?: Prisma.ApeWhereInput
  none?: Prisma.ApeWhereInput
}

export type ApeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ApeOrderByRelevanceInput = {
  fields: Prisma.ApeOrderByRelevanceFieldEnum | Prisma.ApeOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ApeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  condition?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  location?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  updatedById?: Prisma.SortOrder
}

export type ApeAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  updatedById?: Prisma.SortOrder
}

export type ApeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  condition?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  location?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  updatedById?: Prisma.SortOrder
}

export type ApeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  condition?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  location?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  updatedById?: Prisma.SortOrder
}

export type ApeSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  updatedById?: Prisma.SortOrder
}

export type ApeCreateNestedManyWithoutUpdatedByInput = {
  create?: Prisma.XOR<Prisma.ApeCreateWithoutUpdatedByInput, Prisma.ApeUncheckedCreateWithoutUpdatedByInput> | Prisma.ApeCreateWithoutUpdatedByInput[] | Prisma.ApeUncheckedCreateWithoutUpdatedByInput[]
  connectOrCreate?: Prisma.ApeCreateOrConnectWithoutUpdatedByInput | Prisma.ApeCreateOrConnectWithoutUpdatedByInput[]
  createMany?: Prisma.ApeCreateManyUpdatedByInputEnvelope
  connect?: Prisma.ApeWhereUniqueInput | Prisma.ApeWhereUniqueInput[]
}

export type ApeUncheckedCreateNestedManyWithoutUpdatedByInput = {
  create?: Prisma.XOR<Prisma.ApeCreateWithoutUpdatedByInput, Prisma.ApeUncheckedCreateWithoutUpdatedByInput> | Prisma.ApeCreateWithoutUpdatedByInput[] | Prisma.ApeUncheckedCreateWithoutUpdatedByInput[]
  connectOrCreate?: Prisma.ApeCreateOrConnectWithoutUpdatedByInput | Prisma.ApeCreateOrConnectWithoutUpdatedByInput[]
  createMany?: Prisma.ApeCreateManyUpdatedByInputEnvelope
  connect?: Prisma.ApeWhereUniqueInput | Prisma.ApeWhereUniqueInput[]
}

export type ApeUpdateManyWithoutUpdatedByNestedInput = {
  create?: Prisma.XOR<Prisma.ApeCreateWithoutUpdatedByInput, Prisma.ApeUncheckedCreateWithoutUpdatedByInput> | Prisma.ApeCreateWithoutUpdatedByInput[] | Prisma.ApeUncheckedCreateWithoutUpdatedByInput[]
  connectOrCreate?: Prisma.ApeCreateOrConnectWithoutUpdatedByInput | Prisma.ApeCreateOrConnectWithoutUpdatedByInput[]
  upsert?: Prisma.ApeUpsertWithWhereUniqueWithoutUpdatedByInput | Prisma.ApeUpsertWithWhereUniqueWithoutUpdatedByInput[]
  createMany?: Prisma.ApeCreateManyUpdatedByInputEnvelope
  set?: Prisma.ApeWhereUniqueInput | Prisma.ApeWhereUniqueInput[]
  disconnect?: Prisma.ApeWhereUniqueInput | Prisma.ApeWhereUniqueInput[]
  delete?: Prisma.ApeWhereUniqueInput | Prisma.ApeWhereUniqueInput[]
  connect?: Prisma.ApeWhereUniqueInput | Prisma.ApeWhereUniqueInput[]
  update?: Prisma.ApeUpdateWithWhereUniqueWithoutUpdatedByInput | Prisma.ApeUpdateWithWhereUniqueWithoutUpdatedByInput[]
  updateMany?: Prisma.ApeUpdateManyWithWhereWithoutUpdatedByInput | Prisma.ApeUpdateManyWithWhereWithoutUpdatedByInput[]
  deleteMany?: Prisma.ApeScalarWhereInput | Prisma.ApeScalarWhereInput[]
}

export type ApeUncheckedUpdateManyWithoutUpdatedByNestedInput = {
  create?: Prisma.XOR<Prisma.ApeCreateWithoutUpdatedByInput, Prisma.ApeUncheckedCreateWithoutUpdatedByInput> | Prisma.ApeCreateWithoutUpdatedByInput[] | Prisma.ApeUncheckedCreateWithoutUpdatedByInput[]
  connectOrCreate?: Prisma.ApeCreateOrConnectWithoutUpdatedByInput | Prisma.ApeCreateOrConnectWithoutUpdatedByInput[]
  upsert?: Prisma.ApeUpsertWithWhereUniqueWithoutUpdatedByInput | Prisma.ApeUpsertWithWhereUniqueWithoutUpdatedByInput[]
  createMany?: Prisma.ApeCreateManyUpdatedByInputEnvelope
  set?: Prisma.ApeWhereUniqueInput | Prisma.ApeWhereUniqueInput[]
  disconnect?: Prisma.ApeWhereUniqueInput | Prisma.ApeWhereUniqueInput[]
  delete?: Prisma.ApeWhereUniqueInput | Prisma.ApeWhereUniqueInput[]
  connect?: Prisma.ApeWhereUniqueInput | Prisma.ApeWhereUniqueInput[]
  update?: Prisma.ApeUpdateWithWhereUniqueWithoutUpdatedByInput | Prisma.ApeUpdateWithWhereUniqueWithoutUpdatedByInput[]
  updateMany?: Prisma.ApeUpdateManyWithWhereWithoutUpdatedByInput | Prisma.ApeUpdateManyWithWhereWithoutUpdatedByInput[]
  deleteMany?: Prisma.ApeScalarWhereInput | Prisma.ApeScalarWhereInput[]
}

export type ApeCreateWithoutUpdatedByInput = {
  name: string
  condition?: string | null
  quantity?: number
  location?: string | null
  updatedAt?: Date | string
}

export type ApeUncheckedCreateWithoutUpdatedByInput = {
  id?: number
  name: string
  condition?: string | null
  quantity?: number
  location?: string | null
  updatedAt?: Date | string
}

export type ApeCreateOrConnectWithoutUpdatedByInput = {
  where: Prisma.ApeWhereUniqueInput
  create: Prisma.XOR<Prisma.ApeCreateWithoutUpdatedByInput, Prisma.ApeUncheckedCreateWithoutUpdatedByInput>
}

export type ApeCreateManyUpdatedByInputEnvelope = {
  data: Prisma.ApeCreateManyUpdatedByInput | Prisma.ApeCreateManyUpdatedByInput[]
  skipDuplicates?: boolean
}

export type ApeUpsertWithWhereUniqueWithoutUpdatedByInput = {
  where: Prisma.ApeWhereUniqueInput
  update: Prisma.XOR<Prisma.ApeUpdateWithoutUpdatedByInput, Prisma.ApeUncheckedUpdateWithoutUpdatedByInput>
  create: Prisma.XOR<Prisma.ApeCreateWithoutUpdatedByInput, Prisma.ApeUncheckedCreateWithoutUpdatedByInput>
}

export type ApeUpdateWithWhereUniqueWithoutUpdatedByInput = {
  where: Prisma.ApeWhereUniqueInput
  data: Prisma.XOR<Prisma.ApeUpdateWithoutUpdatedByInput, Prisma.ApeUncheckedUpdateWithoutUpdatedByInput>
}

export type ApeUpdateManyWithWhereWithoutUpdatedByInput = {
  where: Prisma.ApeScalarWhereInput
  data: Prisma.XOR<Prisma.ApeUpdateManyMutationInput, Prisma.ApeUncheckedUpdateManyWithoutUpdatedByInput>
}

export type ApeScalarWhereInput = {
  AND?: Prisma.ApeScalarWhereInput | Prisma.ApeScalarWhereInput[]
  OR?: Prisma.ApeScalarWhereInput[]
  NOT?: Prisma.ApeScalarWhereInput | Prisma.ApeScalarWhereInput[]
  id?: Prisma.IntFilter<"Ape"> | number
  name?: Prisma.StringFilter<"Ape"> | string
  condition?: Prisma.StringNullableFilter<"Ape"> | string | null
  quantity?: Prisma.IntFilter<"Ape"> | number
  location?: Prisma.StringNullableFilter<"Ape"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"Ape"> | Date | string
  updatedById?: Prisma.IntFilter<"Ape"> | number
}

export type ApeCreateManyUpdatedByInput = {
  id?: number
  name: string
  condition?: string | null
  quantity?: number
  location?: string | null
  updatedAt?: Date | string
}

export type ApeUpdateWithoutUpdatedByInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  condition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApeUncheckedUpdateWithoutUpdatedByInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  condition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApeUncheckedUpdateManyWithoutUpdatedByInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  condition?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ApeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  condition?: boolean
  quantity?: boolean
  location?: boolean
  updatedAt?: boolean
  updatedById?: boolean
  updatedBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ape"]>



export type ApeSelectScalar = {
  id?: boolean
  name?: boolean
  condition?: boolean
  quantity?: boolean
  location?: boolean
  updatedAt?: boolean
  updatedById?: boolean
}

export type ApeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "condition" | "quantity" | "location" | "updatedAt" | "updatedById", ExtArgs["result"]["ape"]>
export type ApeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  updatedBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $ApePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Ape"
  objects: {
    updatedBy: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    condition: string | null
    quantity: number
    location: string | null
    updatedAt: Date
    updatedById: number
  }, ExtArgs["result"]["ape"]>
  composites: {}
}

export type ApeGetPayload<S extends boolean | null | undefined | ApeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ApePayload, S>

export type ApeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ApeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ApeCountAggregateInputType | true
  }

export interface ApeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Ape'], meta: { name: 'Ape' } }
  /**
   * Find zero or one Ape that matches the filter.
   * @param {ApeFindUniqueArgs} args - Arguments to find a Ape
   * @example
   * // Get one Ape
   * const ape = await prisma.ape.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ApeFindUniqueArgs>(args: Prisma.SelectSubset<T, ApeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ApeClient<runtime.Types.Result.GetResult<Prisma.$ApePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Ape that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ApeFindUniqueOrThrowArgs} args - Arguments to find a Ape
   * @example
   * // Get one Ape
   * const ape = await prisma.ape.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ApeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ApeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApeClient<runtime.Types.Result.GetResult<Prisma.$ApePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Ape that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApeFindFirstArgs} args - Arguments to find a Ape
   * @example
   * // Get one Ape
   * const ape = await prisma.ape.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ApeFindFirstArgs>(args?: Prisma.SelectSubset<T, ApeFindFirstArgs<ExtArgs>>): Prisma.Prisma__ApeClient<runtime.Types.Result.GetResult<Prisma.$ApePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Ape that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApeFindFirstOrThrowArgs} args - Arguments to find a Ape
   * @example
   * // Get one Ape
   * const ape = await prisma.ape.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ApeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ApeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApeClient<runtime.Types.Result.GetResult<Prisma.$ApePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Apes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Apes
   * const apes = await prisma.ape.findMany()
   * 
   * // Get first 10 Apes
   * const apes = await prisma.ape.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const apeWithIdOnly = await prisma.ape.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ApeFindManyArgs>(args?: Prisma.SelectSubset<T, ApeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Ape.
   * @param {ApeCreateArgs} args - Arguments to create a Ape.
   * @example
   * // Create one Ape
   * const Ape = await prisma.ape.create({
   *   data: {
   *     // ... data to create a Ape
   *   }
   * })
   * 
   */
  create<T extends ApeCreateArgs>(args: Prisma.SelectSubset<T, ApeCreateArgs<ExtArgs>>): Prisma.Prisma__ApeClient<runtime.Types.Result.GetResult<Prisma.$ApePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Apes.
   * @param {ApeCreateManyArgs} args - Arguments to create many Apes.
   * @example
   * // Create many Apes
   * const ape = await prisma.ape.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ApeCreateManyArgs>(args?: Prisma.SelectSubset<T, ApeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Ape.
   * @param {ApeDeleteArgs} args - Arguments to delete one Ape.
   * @example
   * // Delete one Ape
   * const Ape = await prisma.ape.delete({
   *   where: {
   *     // ... filter to delete one Ape
   *   }
   * })
   * 
   */
  delete<T extends ApeDeleteArgs>(args: Prisma.SelectSubset<T, ApeDeleteArgs<ExtArgs>>): Prisma.Prisma__ApeClient<runtime.Types.Result.GetResult<Prisma.$ApePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Ape.
   * @param {ApeUpdateArgs} args - Arguments to update one Ape.
   * @example
   * // Update one Ape
   * const ape = await prisma.ape.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ApeUpdateArgs>(args: Prisma.SelectSubset<T, ApeUpdateArgs<ExtArgs>>): Prisma.Prisma__ApeClient<runtime.Types.Result.GetResult<Prisma.$ApePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Apes.
   * @param {ApeDeleteManyArgs} args - Arguments to filter Apes to delete.
   * @example
   * // Delete a few Apes
   * const { count } = await prisma.ape.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ApeDeleteManyArgs>(args?: Prisma.SelectSubset<T, ApeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Apes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Apes
   * const ape = await prisma.ape.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ApeUpdateManyArgs>(args: Prisma.SelectSubset<T, ApeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Ape.
   * @param {ApeUpsertArgs} args - Arguments to update or create a Ape.
   * @example
   * // Update or create a Ape
   * const ape = await prisma.ape.upsert({
   *   create: {
   *     // ... data to create a Ape
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Ape we want to update
   *   }
   * })
   */
  upsert<T extends ApeUpsertArgs>(args: Prisma.SelectSubset<T, ApeUpsertArgs<ExtArgs>>): Prisma.Prisma__ApeClient<runtime.Types.Result.GetResult<Prisma.$ApePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Apes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApeCountArgs} args - Arguments to filter Apes to count.
   * @example
   * // Count the number of Apes
   * const count = await prisma.ape.count({
   *   where: {
   *     // ... the filter for the Apes we want to count
   *   }
   * })
  **/
  count<T extends ApeCountArgs>(
    args?: Prisma.Subset<T, ApeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ApeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Ape.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ApeAggregateArgs>(args: Prisma.Subset<T, ApeAggregateArgs>): Prisma.PrismaPromise<GetApeAggregateType<T>>

  /**
   * Group by Ape.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ApeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ApeGroupByArgs['orderBy'] }
      : { orderBy?: ApeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ApeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetApeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Ape model
 */
readonly fields: ApeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Ape.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ApeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  updatedBy<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Ape model
 */
export interface ApeFieldRefs {
  readonly id: Prisma.FieldRef<"Ape", 'Int'>
  readonly name: Prisma.FieldRef<"Ape", 'String'>
  readonly condition: Prisma.FieldRef<"Ape", 'String'>
  readonly quantity: Prisma.FieldRef<"Ape", 'Int'>
  readonly location: Prisma.FieldRef<"Ape", 'String'>
  readonly updatedAt: Prisma.FieldRef<"Ape", 'DateTime'>
  readonly updatedById: Prisma.FieldRef<"Ape", 'Int'>
}
    

// Custom InputTypes
/**
 * Ape findUnique
 */
export type ApeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ape
   */
  select?: Prisma.ApeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ape
   */
  omit?: Prisma.ApeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApeInclude<ExtArgs> | null
  /**
   * Filter, which Ape to fetch.
   */
  where: Prisma.ApeWhereUniqueInput
}

/**
 * Ape findUniqueOrThrow
 */
export type ApeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ape
   */
  select?: Prisma.ApeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ape
   */
  omit?: Prisma.ApeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApeInclude<ExtArgs> | null
  /**
   * Filter, which Ape to fetch.
   */
  where: Prisma.ApeWhereUniqueInput
}

/**
 * Ape findFirst
 */
export type ApeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ape
   */
  select?: Prisma.ApeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ape
   */
  omit?: Prisma.ApeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApeInclude<ExtArgs> | null
  /**
   * Filter, which Ape to fetch.
   */
  where?: Prisma.ApeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Apes to fetch.
   */
  orderBy?: Prisma.ApeOrderByWithRelationInput | Prisma.ApeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Apes.
   */
  cursor?: Prisma.ApeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Apes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Apes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Apes.
   */
  distinct?: Prisma.ApeScalarFieldEnum | Prisma.ApeScalarFieldEnum[]
}

/**
 * Ape findFirstOrThrow
 */
export type ApeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ape
   */
  select?: Prisma.ApeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ape
   */
  omit?: Prisma.ApeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApeInclude<ExtArgs> | null
  /**
   * Filter, which Ape to fetch.
   */
  where?: Prisma.ApeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Apes to fetch.
   */
  orderBy?: Prisma.ApeOrderByWithRelationInput | Prisma.ApeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Apes.
   */
  cursor?: Prisma.ApeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Apes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Apes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Apes.
   */
  distinct?: Prisma.ApeScalarFieldEnum | Prisma.ApeScalarFieldEnum[]
}

/**
 * Ape findMany
 */
export type ApeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ape
   */
  select?: Prisma.ApeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ape
   */
  omit?: Prisma.ApeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApeInclude<ExtArgs> | null
  /**
   * Filter, which Apes to fetch.
   */
  where?: Prisma.ApeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Apes to fetch.
   */
  orderBy?: Prisma.ApeOrderByWithRelationInput | Prisma.ApeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Apes.
   */
  cursor?: Prisma.ApeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Apes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Apes.
   */
  skip?: number
  distinct?: Prisma.ApeScalarFieldEnum | Prisma.ApeScalarFieldEnum[]
}

/**
 * Ape create
 */
export type ApeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ape
   */
  select?: Prisma.ApeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ape
   */
  omit?: Prisma.ApeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApeInclude<ExtArgs> | null
  /**
   * The data needed to create a Ape.
   */
  data: Prisma.XOR<Prisma.ApeCreateInput, Prisma.ApeUncheckedCreateInput>
}

/**
 * Ape createMany
 */
export type ApeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Apes.
   */
  data: Prisma.ApeCreateManyInput | Prisma.ApeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Ape update
 */
export type ApeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ape
   */
  select?: Prisma.ApeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ape
   */
  omit?: Prisma.ApeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApeInclude<ExtArgs> | null
  /**
   * The data needed to update a Ape.
   */
  data: Prisma.XOR<Prisma.ApeUpdateInput, Prisma.ApeUncheckedUpdateInput>
  /**
   * Choose, which Ape to update.
   */
  where: Prisma.ApeWhereUniqueInput
}

/**
 * Ape updateMany
 */
export type ApeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Apes.
   */
  data: Prisma.XOR<Prisma.ApeUpdateManyMutationInput, Prisma.ApeUncheckedUpdateManyInput>
  /**
   * Filter which Apes to update
   */
  where?: Prisma.ApeWhereInput
  /**
   * Limit how many Apes to update.
   */
  limit?: number
}

/**
 * Ape upsert
 */
export type ApeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ape
   */
  select?: Prisma.ApeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ape
   */
  omit?: Prisma.ApeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApeInclude<ExtArgs> | null
  /**
   * The filter to search for the Ape to update in case it exists.
   */
  where: Prisma.ApeWhereUniqueInput
  /**
   * In case the Ape found by the `where` argument doesn't exist, create a new Ape with this data.
   */
  create: Prisma.XOR<Prisma.ApeCreateInput, Prisma.ApeUncheckedCreateInput>
  /**
   * In case the Ape was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ApeUpdateInput, Prisma.ApeUncheckedUpdateInput>
}

/**
 * Ape delete
 */
export type ApeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ape
   */
  select?: Prisma.ApeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ape
   */
  omit?: Prisma.ApeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApeInclude<ExtArgs> | null
  /**
   * Filter which Ape to delete.
   */
  where: Prisma.ApeWhereUniqueInput
}

/**
 * Ape deleteMany
 */
export type ApeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Apes to delete
   */
  where?: Prisma.ApeWhereInput
  /**
   * Limit how many Apes to delete.
   */
  limit?: number
}

/**
 * Ape without action
 */
export type ApeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ape
   */
  select?: Prisma.ApeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ape
   */
  omit?: Prisma.ApeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApeInclude<ExtArgs> | null
}
