
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  User: 'User',
  Student: 'Student',
  Report: 'Report',
  Document: 'Document',
  Anecdote: 'Anecdote',
  Question: 'Question',
  Ape: 'Ape',
  ActivityLog: 'ActivityLog'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  passwordHash: 'passwordHash',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const StudentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  identifier: 'identifier',
  photoUrl: 'photoUrl',
  className: 'className',
  parentName: 'parentName',
  parentPhone: 'parentPhone',
  address: 'address',
  createdAt: 'createdAt'
} as const

export type StudentScalarFieldEnum = (typeof StudentScalarFieldEnum)[keyof typeof StudentScalarFieldEnum]


export const ReportScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  photoUrl: 'photoUrl',
  date: 'date',
  createdAt: 'createdAt',
  studentId: 'studentId',
  teacherId: 'teacherId'
} as const

export type ReportScalarFieldEnum = (typeof ReportScalarFieldEnum)[keyof typeof ReportScalarFieldEnum]


export const DocumentScalarFieldEnum = {
  id: 'id',
  title: 'title',
  category: 'category',
  filePath: 'filePath',
  uploadedAt: 'uploadedAt',
  uploadedById: 'uploadedById'
} as const

export type DocumentScalarFieldEnum = (typeof DocumentScalarFieldEnum)[keyof typeof DocumentScalarFieldEnum]


export const AnecdoteScalarFieldEnum = {
  id: 'id',
  content: 'content',
  date: 'date',
  imageUrl: 'imageUrl',
  teacherId: 'teacherId',
  studentId: 'studentId'
} as const

export type AnecdoteScalarFieldEnum = (typeof AnecdoteScalarFieldEnum)[keyof typeof AnecdoteScalarFieldEnum]


export const QuestionScalarFieldEnum = {
  id: 'id',
  text: 'text',
  imageUrl: 'imageUrl',
  createdAt: 'createdAt',
  teacherId: 'teacherId'
} as const

export type QuestionScalarFieldEnum = (typeof QuestionScalarFieldEnum)[keyof typeof QuestionScalarFieldEnum]


export const ApeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  condition: 'condition',
  quantity: 'quantity',
  location: 'location',
  updatedAt: 'updatedAt',
  updatedById: 'updatedById'
} as const

export type ApeScalarFieldEnum = (typeof ApeScalarFieldEnum)[keyof typeof ApeScalarFieldEnum]


export const ActivityLogScalarFieldEnum = {
  id: 'id',
  action: 'action',
  entity: 'entity',
  entityId: 'entityId',
  metadata: 'metadata',
  createdAt: 'createdAt',
  userId: 'userId'
} as const

export type ActivityLogScalarFieldEnum = (typeof ActivityLogScalarFieldEnum)[keyof typeof ActivityLogScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const UserOrderByRelevanceFieldEnum = {
  name: 'name',
  email: 'email',
  passwordHash: 'passwordHash'
} as const

export type UserOrderByRelevanceFieldEnum = (typeof UserOrderByRelevanceFieldEnum)[keyof typeof UserOrderByRelevanceFieldEnum]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const StudentOrderByRelevanceFieldEnum = {
  name: 'name',
  identifier: 'identifier',
  photoUrl: 'photoUrl',
  className: 'className',
  parentName: 'parentName',
  parentPhone: 'parentPhone',
  address: 'address'
} as const

export type StudentOrderByRelevanceFieldEnum = (typeof StudentOrderByRelevanceFieldEnum)[keyof typeof StudentOrderByRelevanceFieldEnum]


export const ReportOrderByRelevanceFieldEnum = {
  title: 'title',
  description: 'description',
  photoUrl: 'photoUrl'
} as const

export type ReportOrderByRelevanceFieldEnum = (typeof ReportOrderByRelevanceFieldEnum)[keyof typeof ReportOrderByRelevanceFieldEnum]


export const DocumentOrderByRelevanceFieldEnum = {
  title: 'title',
  category: 'category',
  filePath: 'filePath'
} as const

export type DocumentOrderByRelevanceFieldEnum = (typeof DocumentOrderByRelevanceFieldEnum)[keyof typeof DocumentOrderByRelevanceFieldEnum]


export const AnecdoteOrderByRelevanceFieldEnum = {
  content: 'content',
  imageUrl: 'imageUrl'
} as const

export type AnecdoteOrderByRelevanceFieldEnum = (typeof AnecdoteOrderByRelevanceFieldEnum)[keyof typeof AnecdoteOrderByRelevanceFieldEnum]


export const QuestionOrderByRelevanceFieldEnum = {
  text: 'text',
  imageUrl: 'imageUrl'
} as const

export type QuestionOrderByRelevanceFieldEnum = (typeof QuestionOrderByRelevanceFieldEnum)[keyof typeof QuestionOrderByRelevanceFieldEnum]


export const ApeOrderByRelevanceFieldEnum = {
  name: 'name',
  condition: 'condition',
  location: 'location'
} as const

export type ApeOrderByRelevanceFieldEnum = (typeof ApeOrderByRelevanceFieldEnum)[keyof typeof ApeOrderByRelevanceFieldEnum]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const ActivityLogOrderByRelevanceFieldEnum = {
  action: 'action',
  entity: 'entity'
} as const

export type ActivityLogOrderByRelevanceFieldEnum = (typeof ActivityLogOrderByRelevanceFieldEnum)[keyof typeof ActivityLogOrderByRelevanceFieldEnum]

