
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Student
 * 
 */
export type Student = Prisma.StudentModel
/**
 * Model Report
 * 
 */
export type Report = Prisma.ReportModel
/**
 * Model Document
 * 
 */
export type Document = Prisma.DocumentModel
/**
 * Model Anecdote
 * 
 */
export type Anecdote = Prisma.AnecdoteModel
/**
 * Model Question
 * 
 */
export type Question = Prisma.QuestionModel
/**
 * Model Ape
 * 
 */
export type Ape = Prisma.ApeModel
/**
 * Model ActivityLog
 * 
 */
export type ActivityLog = Prisma.ActivityLogModel
