
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User.ts'
export type * from './models/Student.ts'
export type * from './models/Report.ts'
export type * from './models/Document.ts'
export type * from './models/Anecdote.ts'
export type * from './models/Question.ts'
export type * from './models/Ape.ts'
export type * from './models/ActivityLog.ts'
export type * from './commonInputTypes.ts'